# Generated by Django 4.0.1 on 2022-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_set_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='rpe',
            field=models.IntegerField(max_length=3, null=True, verbose_name='RPE'),
        ),
    ]
