# Generated by Django 4.0.1 on 2022-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_set_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.IntegerField(null=True, verbose_name='Reps'),
        ),
        migrations.AddField(
            model_name='set',
            name='sets',
            field=models.IntegerField(null=True, verbose_name='Sets'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='rpe',
            field=models.IntegerField(default=80, max_length=3, null=True, verbose_name='RPE'),
        ),
    ]
