# Generated by Django 4.0.1 on 2022-03-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_set_reps_set_sets_alter_set_name_alter_set_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emaiL_address',
            new_name='email_address',
        ),
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=5, null=True, verbose_name='Reps'),
        ),
        migrations.AlterField(
            model_name='set',
            name='sets',
            field=models.IntegerField(default=4, null=True, verbose_name='Sets'),
        ),
        migrations.CreateModel(
            name='BlockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.block')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.movement')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workouts.user'),
        ),
    ]
